ci(secret): Changed the package used for detecting secrets

diff --git a/.github/workflows/detect-secrets.yml b/.github/workflows/detect-secrets.yml
--- a/.github/workflows/detect-secrets.yml
+++ b/.github/workflows/detect-secrets.yml
@@ -1,32 +1,56 @@
-name: Detect Secrets
+# name: Detect Secrets
+
+# on:
+#   push:
+#     branches:
+#       - "feat/setup"
+#   pull_request:
+#     branches:
+#     - "develop"
+#     - "staging"
+#     - "main"
+
+# jobs:
+#   detect-secrets:
+#     runs-on: ubuntu-latest
+#     steps:
+#       - name: Checkout repository
+#         uses: actions/checkout@v3
+
+#       - name: Set up Python
+#         uses: actions/setup-python@v4
+#         with:
+#           python-version: '3.10'
+
+#       - name: Install Detect-Secrets
+#         run: |
+#           pip install detect-secrets
+
+#       - name: Run Detect-Secrets
+#         run: |
+#           detect-secrets scan
+#           detect-secrets scan --baseline .secrets.baseline || (echo "Secrets detected! Failing the workflow." && exit 1)
+name: Secretlint Scan
 
 on:
   push:
     branches:
-      - "feat/setup"
+      - feat/setup
   pull_request:
     branches:
-    - "develop"
-    - "staging"
-    - "main"
+      - feat/setup
 
 jobs:
-  detect-secrets:
+  secretlint:
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout repository
-        uses: actions/checkout@v3
+      - name: Checkout code
+        uses: actions/checkout@v2
 
-      - name: Set up Python
-        uses: actions/setup-python@v4
-        with:
-          python-version: '3.10'
-
-      - name: Install Detect-Secrets
+      - name: Install secretlint
         run: |
-          pip install detect-secrets
+          npm install -g secretlint
 
-      - name: Run Detect-Secrets
+      - name: Run secretlint
         run: |
-          detect-secrets scan
-          detect-secrets scan --baseline .secrets.baseline || (echo "Secrets detected! Failing the workflow." && exit 1)
+          secretlint '**/*.ts' '**/*.js' '**/*.tsx'
